### ISSUE TITLE
Highlighted text disappears when refreshing the page

### ISSUE THREAD

**Issue by angelogalanti** [jeromepl/highlighter#17]
The extension no longer works for me. Now when I refresh the page the highlighted text is no longer there.

**Comment by jeromepl** [comment]
Hi,
The extension hasn't been updated in a few months so it is possible that the website you were highlighting on has had an update that broke the highlights you had.
Can you send me some example(s) of website where the extension does not work for you?

**Comment by angelogalanti** [comment]
Apologies. I cannot seem to reproduce the error. Well, at least it is solved!

**Comment by jeromepl** [comment]
Ok no problem, let me know if it happens again!
