### ISSUE TITLE
[Feature Request] Copy All Highlights

### ISSUE THREAD

**Issue by jeromepl** [jeromepl/highlighter#2]
Add a way to copy all highlighted text to the user's clipboard.
Feature requested through a chrome web store review.

**Comment by netrebel** [comment]
This would be awesome! This can be done in Apps like Instapaper, after saving the web page to their service.

**Comment by jeromepl** [comment]
I am working on an update that should address this and #6 ! Hopefully I can find enough time to have a new release in a few weeks

**Comment by jeromepl** [comment]
This is now live in v3.0!

**Comment by netrebel** [comment]
I can navigate the page according to the highlights! Nice, thanks for adding this. 🙏 
![image](https://user-images.githubusercontent.com/294448/88420461-ca8bb580-cd9b-11ea-8594-3c80e064395b.png)
