### ISSUE TITLE
[Feature Request] Highlight colors for dark mode

### ISSUE THREAD

**Issue by OLucasZanella** [jeromepl/highlighter#20]
This extension is precisely what I was looking for, except for one caveat: I'm always using the Dark Reader extension, which makes all web pages dark.

Since the text becomes white, highlighting it with the light colors available renders it almost impossible to read. Would it be possible to add some options for white text as well? One single custom color option would also do the trick.

**Comment by sfd99** [comment]
I totally agree 
with OLucasZanella, (request above).

I use DARK MODE in Chrome,
for limited eyesight
and the text  in  highlighted items 
are extremely hard to read, 
(they appear as gray text). 

Option to **change the color** of the TEXT
inside a highlight , 
  _ie: white to black text and vice-versa,_
would be VERY HELPFUL to many of us.

_Please Jerome, do it._
Thank you/Merci!.

**SFd99
San Francisco.
latest Chrome
Ubuntu Linux 20.04**

**Comment by jeromepl** [comment]
I have added a feature to customize highlight colors **and** the text color in the highlights. This should resolve the issue with dark mode!
Expect this to be released in v4 in early January 🙂

**Comment by OLucasZanella** [comment]
Awesome, I'm sure it will be useful!

Unfortunately, I'm using Firefox at the moment, but if I ever get to Chrome, I'll be using this extension again, it's great.
