### ISSUE TITLE
Allow user to set a DEFAULT highlight color (instead of always Yellow)

### ISSUE THREAD

**Issue by sfd99** [jeromepl/highlighter#34]
Hi Jerome,

Highlighter 401
is awesome! .

Simple **Important** suggestion:
**==>** Allow user to select a **default highlight color** in options.
Highly useful for many of your Users!!.

Reason:
Every time I select and ALT+H
a text on the page, 
Highlighter forces me to accept YELLOW 
as a default color..

But my favorite highlight BKG color choice
is lilac = violet.
Much more readable in my case...

So, **every time I highlight**
I have to **manually select:** lilac
from the Highlighter Color Palette...

Instead,
I need lilac 
to be my default highlighting color!.

Hope you can include 
this important **color default** option,
as soon as possible.

Merci  / Thanks Jerome!.
**SFd99
San Francisco**

**Comment by jeromepl** [comment]
Hi! Sorry for the late reply on this.
I believe this functionality should already work.
If you click on the Highlighter icon in your list of Chrome extensions (see screenshot), and select a color other than Yellow, it should be the color used by default when using the keyboard shortcut Alt+H.
![image](https://user-images.githubusercontent.com/7671307/160289245-f524269c-e71f-4be2-b96a-d82f25bc2549.png)

Testing on my computer, it seems to be working fine, let me know if you are not able to reproduce in which case this could be a bug

**Comment by sfd99** [comment]
**Hi Jerome,**

**PERFECT!.** 
Now, I can  finally set 
my fav default color **permanently**.

I did not see this "Default Color" option,
because the "Highlighter" ext ICON
is not included
in my [ Extensions Bar ] in Chrome.

**Reason:**
My Chrome [ Extension Bar ]
is already over-populated,
so I prefer not showing 
_every_ Extension Icon... :-)

I just use it as needed
with kbd shortcut:
 **ALT+H...**

So now,
with your good advice,
it works GREAT!!.
YAY!.

**Merci / Thanks Jerome!.
Have a super day...
(if that is _even possible_, nowadays...).

SFd99
San Francisco
Latest Chrome, Ubuntu Linux 20.04**

**Comment by jeromepl** [comment]
Awesome, glad to hear this solved your issue 🙂
