### ISSUE TITLE
[BUG] highlighter remove space between two cylables words

### ISSUE THREAD

**Issue by Alirezaaraby** [jeromepl/highlighter#42]
hi, check out this [link](https://www.scientificamerican.com/podcast/episode/how-the-pandemic-shortened-life-expectancy-and-new-drugs-on-the-horizon-covid-quickly-episode-40/). there's a problem here when I highlight a two-syllable word like `chronic liver` it removes the white space between each syllable.

### System log
browser: Chrome 106.0.5249.119 (Official Build) (64-bit) (cohort: Stable)

**Comment by jeromepl** [comment]
Could you show me what it looks like on your end? Can you give me more examples of when this happens?
When I try on my side, it looks like this: 

![image](https://user-images.githubusercontent.com/7671307/197370621-d5bb1fd5-6062-4c8e-9a49-a95c108f59b7.png)

**Comment by Alirezaaraby** [comment]
it's like this:
![image](https://user-images.githubusercontent.com/45128978/197386929-60e3afa9-59dc-4b93-b2c6-c988b7b2c2da.png)

**Comment by Alirezaaraby** [comment]
same problem with the below link
[![image](https://user-images.githubusercontent.com/45128978/204125775-92ffbb23-4568-4b31-ae73-faf5d646fac1.png)
](https://www.scientificamerican.com/podcast/episode/antivirals-could-reduce-long-covid-risk-and-how-well-the-new-boosters-work-covid-quickly-podcast-episode-43/#:~:text=Moderna%20results%20are-,in,line%20with,-a%20number)

**Comment by jeromepl** [comment]
I believe I have found the issue causing this, it should be resolved for any new highlights after v5 is merged and released (no set date yet)
