### ISSUE TITLE
Have a sort of archive of all highlighted texts 

### ISSUE THREAD

**Issue by IoanaAMuresan** [jeromepl/highlighter#61]
Ok, I'm a dreamer :) - but I'd love to be able to do this: 

When clicking on the extension menu - have a link to My collection -> a page where I'd see all my highlights with links to the original source, grouped by page, but filterable by color, date, site, and with a keyword search too 

I'm not a dev, so... this is as far as I can go :)) - but happy to test and provide feedback if ever :) 

PS Great extension - life saver!

**Comment by jeromepl** [comment]
Hi and thanks for the interest in the extension!
You are not the first one to ask for this, in fact, we have issue #6 already tracking this feature request, so you can follow progress on it there and I'll close this one.

But before doing so, would you mind telling me if this is something you'd be willing to pay a small subscription fee for? Adding bigger features like this one and supporting them is something I'd love to dedicate more time to but is difficult to do at the moment without financial backing, so putting some new features behind a "pro" subscription is something I am considering and would love your input.
Thanks!
