### ISSUE TITLE
license and using this in my project. 

### ISSUE THREAD

**Issue by Jewcub** [jeromepl/highlighter#9]
### Hello! 
I'm making a flash card app that can create cards from highlights online and I came across your extension. I didn't see a license, and I used some parts of your code in my project. I hope that's alright!
It's an open source project, and if you want to get involved we'd love to have you!
https://github.com/IPFC/
https://github.com/IPFC/ipfc-extension

**Comment by jeromepl** [comment]
Hi! I just added the MIT license to the project, feel free to use the code for whatever you would like!
